# Generated by Django 5.1.1 on 2024-09-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_transactiontype_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='account_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
